sudo: false

language: rust
os:
  - linux
  - windows
  - osx
rust:
  - stable
  - nightly
cache: cargo
env:
  global:
    - RUST_BACKTRACE=1
    - RUSTFLAGS="-D warnings"
    - RUST_LOG="raft=trace,test=trace"

install:
  - if [[ $TRAVIS_RUST_VERSION == "stable" && $TRAVIS_OS_NAME == "linux" ]]; then rustup component add rustfmt; fi
  - if [[ $TRAVIS_RUST_VERSION == "stable" && $TRAVIS_OS_NAME == "linux" ]]; then rustup component add clippy; fi
  # Windows path/dependency tomfoolery.
  - if [[ $TRAVIS_OS_NAME == "windows" ]]; then choco install golang; fi
  - if [[ $TRAVIS_OS_NAME == "windows" ]]; then choco install cmake; fi
  - if [[ $TRAVIS_OS_NAME == "windows" ]]; then export PATH="$PATH:/c/Go/bin/:/c/Program Files/CMake/bin"; fi

before_script:
  # Only check these on stable linux, since we don't want unrelated failures.
  - if [[ $TRAVIS_RUST_VERSION == "stable" && $TRAVIS_OS_NAME == "linux" ]]; then cargo fmt -- --check; fi
  - if [[ $TRAVIS_RUST_VERSION == "stable" && $TRAVIS_OS_NAME == "linux" ]]; then cargo clippy -- -D clippy::all; fi

script:
  - cargo test --all -- --nocapture
  # Validate benches still work.
  - cargo bench --all -- --test
  # Failpoints inject failure in code paths, which will affect all concurrently running tests.
  # They need to be synchronized, which make tests slow.
  - cargo test --tests --features failpoint -- --nocapture